services:
  api:
    build:
      dockerfile: ./server/Dockerfile
      context: .
    container_name: vr_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./app.db:/app/app.db
    env_file:
      - ./server/.env

  app:
    build:
      dockerfile: ./docker/node/Dockerfile
      context: .
    container_name: vr_app
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - .:/app
