"""First migration

Revision ID: 4d7554a6bc00
Revises: 
Create Date: 2024-03-03 08:46:13.948926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d7554a6bc00'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vendos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('api_url', sa.String(), nullable=True),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('total_sales', sa.Float(), nullable=True),
    sa.Column('current_sales', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('vendo_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendo_id', sa.Integer(), nullable=True),
    sa.Column('log_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['vendo_id'], ['vendos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendo_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendo_id', sa.Integer(), nullable=True),
    sa.Column('sale_time', sa.DateTime(), nullable=True),
    sa.Column('mac_address', sa.String(), nullable=True),
    sa.Column('voucher', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['vendo_id'], ['vendos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendo_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendo_id', sa.Integer(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('active_users', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['vendo_id'], ['vendos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendo_status')
    op.drop_table('vendo_sales')
    op.drop_table('vendo_logs')
    op.drop_table('vendos')
    op.drop_table('users')
    # ### end Alembic commands ###
