"""Add columns to vendo_status

Revision ID: 7d48c782ea03
Revises: 3e764100138c
Create Date: 2024-03-10 06:54:11.952469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d48c782ea03'
down_revision: Union[str, None] = '3e764100138c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tests')
    op.add_column('vendo_status', sa.Column('total_sales', sa.Float(), nullable=True))
    op.add_column('vendo_status', sa.Column('current_sales', sa.Float(), nullable=True))
    op.add_column('vendo_status', sa.Column('customer_count', sa.Integer(), nullable=True))
    op.add_column('vendo_status', sa.Column('free_heap', sa.Integer(), nullable=True))
    op.add_column('vendo_status', sa.Column('wireless_strength', sa.Float(), nullable=True))
    op.drop_column('vendo_status', 'is_online')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendo_status', sa.Column('is_online', sa.BOOLEAN(), nullable=True))
    op.drop_column('vendo_status', 'wireless_strength')
    op.drop_column('vendo_status', 'free_heap')
    op.drop_column('vendo_status', 'customer_count')
    op.drop_column('vendo_status', 'current_sales')
    op.drop_column('vendo_status', 'total_sales')
    op.create_table('tests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
