"""Add is_active

Revision ID: 88179bf1371a
Revises: 86b3c2f0b2c5
Create Date: 2024-03-04 05:30:08.858083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88179bf1371a'
down_revision: Union[str, None] = '86b3c2f0b2c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendos', sa.Column('is_active', sa.Integer(), nullable=True, server_default="1"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendos', 'is_active')
    # ### end Alembic commands ###
